version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: movies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
